name: Flake8 test runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run Flake8
      run: |
        pip install flake8
        flake8 ./mayan
